## Intro to NumPy
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays (https://en.wikipedia.org/wiki/NumPy).

Numpy is incredibly fast, as it has bindings to C libraries.

In [1]:
import numpy as np

## Creation of NumPy array
### From a list

In [2]:
a_list = [1, 2, 3]
a_array = np.array(a_list)

In [3]:
print(type(a_list))
print(type(a_array))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
a_2D = np.array(matrix)

### Using built-in methods

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2) # np.arange(start, stop, step)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.linspace(0, 10, 20) # np.linspace(start, stop, num=50)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random

### uniform
Return an array of the given shape with random samples from a uniform distribution

In [10]:
np.random.uniform(0, 1, 5) # (low, high, size)

array([0.04207257, 0.83122271, 0.39221673, 0.74397345, 0.93801783])

### randn
Return samples from the “standard normal” distribution.

In [11]:
np.random.randn(2,2) # standard normal (Gaussian) distribution of mean 0 and variance 1

array([[ 0.8742866 ,  2.38930658],
       [-1.10377893,  0.59820148]])

### normal

In [12]:
mu, sigma = 1, 0.5 # mean and standard deviation
np.random.normal(mu, sigma, size = (3, 2))

array([[0.18106369, 1.13447626],
       [0.66367668, 1.7301693 ],
       [0.59467079, 1.46263351]])

### multivariate normal

In [13]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[-1.09718484,  2.18736797],
        [ 0.46478892,  1.60050889]],

       [[ 1.72953783,  2.68610214],
        [ 2.01276053,  3.03714459]],

       [[ 0.12118728,  0.5889787 ],
        [ 0.98277408,  0.44971885]]])

### randint
Return random integers

In [14]:
np.random.randint(1, 100, 5) # randint(low, high=None, size=None)

array([64, 98, 86, 92, 67])

### seed()
The seed() method is used to initialize the random number generator.

In [15]:
np.random.seed(0)

### Operations

In [16]:
arr = np.arange(0, 10)
arr_r = arr.reshape(2, 5)
print('arr: ')
print(arr)
print('arr_r: ')
print(arr_r)

arr: 
[0 1 2 3 4 5 6 7 8 9]
arr_r: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
my_arr = np.random.randint(1, 100, 10)
print(my_arr)

[45 48 65 68 68 10 84 22 37 88]


In [18]:
my_arr.max()

np.int64(88)

In [19]:
my_arr.argmax()

np.int64(9)

In [20]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [21]:
arr_1 + arr_2

array([5, 7, 9])

In [22]:
arr_1 * arr_2

array([ 4, 10, 18])

In [23]:
np.exp(arr_1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [24]:
np.log(arr_1)

array([0.        , 0.69314718, 1.09861229])