In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
p_list = [1, 2, 3]
p_list

[1, 2, 3]

In [ ]:
np_1d = np.array(p_list)

In [ ]:
np_1d

array([1, 2, 3])

look for the type

In [ ]:
type(p_list)

list

In [ ]:
type(np_1d)

numpy.ndarray

In [ ]:
p_matrix = [[1,2,3],[4,5,6],[7,8,9]]
p_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np_matrix = np.array(p_matrix)
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Using built-in methods

In [ ]:
np.arange(0, 10) # start, stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2) # start, stop, step

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3) # 1D

array([0., 0., 0.])

In [ ]:
np.zeros((3, 5)) # 2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(0, 10, 50) # start, stop, number of elements

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Random value generation

### one value from range 0..1

In [ ]:
rng = np.random.default_rng()
rng.random()

0.05664262406344911

## uniform sequence
Return an array of the given shape with random samples from a uniform distribution

In [ ]:
np.random.uniform(0, 1, 10) # (low, high, size)

array([0.88861308, 0.9926722 , 0.59221836, 0.80757845, 0.24586319,
       0.03865989, 0.53627688, 0.4087244 , 0.05325683, 0.41944488])

### randn
Return samples from the “standard normal” distribution.

In [ ]:
np.random.randn(2,2) # standard normal (Gaussian) distribution of mean 0 and variance 1

array([[ 0.42221077, -1.42504963],
       [ 0.00435896, -0.55343531]])

### normal

In [ ]:
mu, sigma = 1, 0.5 # mean and standard deviation
np.random.normal(mu, sigma, size = (3, 2))

array([[1.00493352, 0.92937006],
       [1.17253197, 0.9126587 ],
       [0.4785441 , 1.27674862]])

### multivariate normal

In [ ]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[ 1.17826695,  3.82396786],
        [ 0.3635501 ,  2.79170543]],

       [[-0.39613835,  1.9658821 ],
        [ 0.85772432,  1.86766777]],

       [[-0.31612454,  1.47551286],
        [ 0.75945679, -0.80834892]]])

### randint
Return random integers

In [ ]:
np.random.randint(1, 100, 5) # randint(low, high=None, size=None)

array([29, 17, 57, 50, 17])

### seed()
The seed() method is used to initialize the random number generator.

In [ ]:
np.random.seed(0)

### Operations

In [ ]:
a1d = np.arange(0, 10)
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2d = a1d.reshape(2, 5) # https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape
a2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
xs = np.random.randint(1, 100, 10)
xs

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [ ]:
xs.mean()

np.float64(53.5)

In [ ]:
xs.max() # value

np.int64(88)

In [ ]:
xs.argmax() # index

np.int64(9)

In [ ]:
xs1 = np.array([1, 2, 3])
xs2 = np.array([4, 5, 6])

In [ ]:
xs1 + xs2 # must have the same length

array([5, 7, 9])

In [ ]:
xs1 * xs2 # must have the same length

array([ 4, 10, 18])

In [ ]:
np.exp(xs1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(xs1)

array([0.        , 0.69314718, 1.09861229])